import type { Metadata } from "next";
import { CssBaseline } from "@mui/material";
import Providers from "./_contexts";
import HeadContent from "./_components/HeadContent";

export const metadata: Metadata = {
  title: "Thomas R. Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Providers>
          <CssBaseline />
          {children}
        </Providers>
      </body>
    </html>
  );
}
